kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32400
    nodePort: 32400
    name: kafka
  - protocol: TCP
    targetPort: 5555
    port: 5555
    nodePort: 5555
    name: jmx
  type: NodePort