kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32401
    nodePort: 32401
    name: kafka
  - protocol: TCP
    targetPort: 5555
    port: 5555
    nodePort: 5555
    name: jmx
  type: NodePort